---
#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role security
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- include: security-ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
