---
#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role test_build_server
#

#
# vars are namespace with the module name.
#
test_build_server_user: jenkins
test_build_server_repo_path: /home/jenkins
