#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
#
#
# Defaults for role devpi
#
---
- name: restart devpi
  supervisorctl_local: >
    state=restarted
    supervisorctl_path={{ devpi_supervisor_ctl }}
    config={{ devpi_supervisor_cfg }}
    name=devpi-server
  sudo_user: "{{ devpi_supervisor_user }}"
