---
#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role testcourses
#
# Overview:
#
#   Imports the testcourses course into studio
#   https://github.com/edx/edx-testcourses-course
#
#   Once imported this role will only re-import the course
#   if the edx-testcourses-course repo has been updated
#
# Dependencies:
#   - common
#   - edxapp
#
# Example play:
#
#   roles:
#     - common
#     - edxapp
#     - testcourses

- include: deploy.yml tags=deploy
