---
#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role test_build_server
#
# Example:
#
# dependencies:
#   - {
#   role: my_role
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }

#### INTENTIONALLY LEFT BLANK ####

# Since this is a test role, it should not install anything extra onto the
# target machine, thus altering the system under test. Be careful when
# adding dependencies.
