---
#
# edX Configuration
#
# github:     https://github.com/TabEd/configuration
# wiki:       https://github.com/TabEd/configuration/wiki
# code style: https://github.com/TabEd/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/TabEd/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role redis
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: add the redis ppa
  apt_repository_1.8: repo="{{ redis_ppa }}" validate_certs=no

- name: install redis system packages
  apt: pkg={{ item }} install_recommends=yes state=present
  with_items: redis_debian_pkgs
  notify: reload redis

- name: update redis configuration
  template: >
    src=etc/redis/redis.conf.j2
    dest=/etc/redis/redis.conf
    owner=root
    group={{ redis_group }}
    mode=640
  notify: reload redis

